Added chaining of cmsRun invocations to farmoutRandomSeedJobs

diff --git a/farmoutRandomSeedJobs b/farmoutRandomSeedJobs
--- a/farmoutRandomSeedJobs
+++ b/farmoutRandomSeedJobs
@@ -5,8 +5,7 @@
 #
 # Usage:
 #       farmoutRandomSeedJobs <jobName> <nEvents> <nEventsPerJob> <CMSSW Version> <config file>
-#       Expects a cfi called IOMC/GeneratorInterface/data/PythiaSource<jobName>.cfi to exist
-#       in the CMSSW area that you are using.
+#
 #  Example: farmoutCmsRunJobs blah 1000000 100 ~/CMSSW_1_2_0 /path/to/my.cfg
 #
 # The config file may refer to the following macros, which are automatically
@@ -99,7 +98,7 @@ check_proxy() {
 }
 
 PrintUsage() {
-  echo "USAGE: farmoutRandomSeedJobs [options] <jobName> <events> <events-per-job> <CMSSW Path> <config file>"
+  echo "USAGE: farmoutRandomSeedJobs [options] <jobName> <events> <events-per-job> <CMSSW Path> <config files>"
   echo ""
   echo "OPTIONS:"
   echo "  --output-dir=${SRM_HOME}/<jobName>"
@@ -158,7 +157,7 @@ do
   shift
 done
 
-if [ "$#" -ne 5 ]; then PrintUsage; fi
+if [ "$#" -lt 5 ]; then PrintUsage; fi
 
 # Check for some required utilities
 for exe in scramv1 condor_submit cmsRun.sh readlink voms-proxy-info; do
@@ -174,6 +173,14 @@ declare -i nEvents=$2
 declare -i nEventsPerJob=$3
 CMSSW_HOME=`realpath $4`
 configTemplate=`realpath $5`
+
+shift 5
+chainedConfigs=""
+while [ "$1" != "" ]; do
+   cfg=`realpath $1`
+   chainedConfigs="$chainedConfigs $cfg"
+   shift
+done
 
 #       Ensure that your environment is correct
 
@@ -224,8 +231,21 @@ for macro in \$randomNumber \$nEventsPerJob \$outputFileName; do
   fi
 done
 
+# Check the chained config templates, if any
+for cfg in ${chainedConfigs}; do
+  ext="${cfg/*./}"
+  if [ "$ext" != "$CFG_EXTENSION" ]; then
+    die "The chained config template $cfg is expected to be the same type of config file as the base config file (${CFG_EXTENSION})."
+  fi
+  for macro in \$inputFileNames \$outputFileName; do
+    if ! grep -F -q $macro $cfg; then
+      die "$macro must appear in the chained configuration template.  I can't find it in $cfg"
+    fi
+  done
+done
+
 # Note: reverse sort order is _very_ important, or the search/replace
-# operation will do the long thing on longer macros having a common
+# operation will do the wrong thing on longer macros having a common
 # prefix with a shorter macro.
 randomMacros=`grep -o '\$randomNumber[0-9]*' $configTemplate | sort -r | uniq`
 
@@ -325,6 +345,12 @@ EOF
 #
 declare -i nEventsSubmitted=0
 declare -i job=0
+
+final_step=1
+for template in $chainedConfigs; do
+  let final_step=$final_step+1
+done
+
 #
 # Loop over jobs
 #
@@ -339,6 +365,12 @@ while (( $nEvents > $nEventsSubmitted )); do
       continue
     fi
 
+    conlog=$jobtag.log
+    stdout=$jobtag.out
+    stderr=$jobtag.err
+    jobcfg=$jobtag.$CFG_EXTENSION
+    outputFileName=$jobtag.root
+
     if [ "$SKIP_EXISTING_OUTPUT" = "1" ]; then
       # Check for existing output file
       if outputFileExists $OUTPUT_DIR/$outputFileName; then
@@ -346,14 +378,10 @@ while (( $nEvents > $nEventsSubmitted )); do
       fi
     fi
 
-    conlog=$jobtag.log
-    stdout=$jobtag.out
-    stderr=$jobtag.err
-    jobcfg=$jobtag.$CFG_EXTENSION
-    outputFileName=$jobtag.root
-    inputfiles="$jobcfg"
-    if [ "$EXTRA_INPUTS" != "" ]; then
-      inputfiles="$jobcfg,$EXTRA_INPUTS"
+    step1_outputFileName=$outputFileName
+    if [ "$chainedConfigs" != "" ]; then
+      jobcfg=$jobtag-step1.$CFG_EXTENSION
+      step1_outputFileName=intermediate/$jobtag-step1.root
     fi
 
     randomSed=""
@@ -374,10 +402,39 @@ while (( $nEvents > $nEventsSubmitted )); do
 # Prepare job configuration file
 #
 
-sed < $configTemplate \
-  "${randomSed}
-   s|\\\$nEventsPerJob|$nEventsPerJob|g;
-   s|\\\$outputFileName|$outputFileName|g" > $jobtag/$jobcfg
+    sed < $configTemplate \
+      "${randomSed}
+       s|\\\$nEventsPerJob|$nEventsPerJob|g;
+       s|\\\$outputFileName|$step1_outputFileName|g" > $jobtag/$jobcfg
+
+
+    jobinputfiles="$jobcfg"
+    jobcfgs="$jobcfg"
+
+    last_outputFileName=$step1_outputFileName
+    step=2
+    for template in $chainedConfigs; do
+      step_cfg=$jobtag-step${step}.$CFG_EXTENSION
+      jobcfgs="$jobcfgs,$step_cfg"
+      step_outputFileName=intermediate/$jobtag-step${step}.root
+      if [ $step -eq $final_step ]; then
+        step_outputFileName=$outputFileName
+      fi
+      jobinputfiles="$jobinputfiles,$step_cfg"
+
+      step_inputFileNames="\"${last_outputFileName}\""
+      sed < $template \
+          "s|\\\$inputFileNames|$step_inputFileNames|g;
+           s|\\\$outputFileName|$step_outputFileName|g" > $jobtag/$step_cfg
+
+
+      last_outputFileName=$step_outputFileName
+      let step=$step+1
+    done
+
+    if [ "$EXTRA_INPUTS" != "" ]; then
+      jobinputfiles="$jobinputfiles,$EXTRA_INPUTS"
+    fi
 
 #
 # Prepare condor submit commands for the job
@@ -385,8 +442,8 @@ sed < $configTemplate \
     cat <<EOF >> $submitFile
 
 InitialDir           = $jobtag
-Arguments            = $jobcfg $outputFileName $OUTPUT_DIR
-Transfer_Input_Files = $inputfiles
+Arguments            = $jobcfgs $outputFileName $OUTPUT_DIR
+Transfer_Input_Files = $jobinputfiles
 output               = $stdout
 error                = $stderr
 Log                  = $conlog
