Add support for HDFS.

diff --git a/farmoutAnalysisJobs b/farmoutAnalysisJobs
--- a/farmoutAnalysisJobs
+++ b/farmoutAnalysisJobs
@@ -19,7 +19,7 @@
 # Initialize default settings:
 
 # for storing output
-SRM_SERVER=srm://cmssrm.hep.wisc.edu:8443
+SRM_SERVER=srm://cmssrm.hep.wisc.edu:8443/srm/managerv2?SFN=
 PNFS_HOME=/pnfs/hep.wisc.edu/store/user/$USER
 
 # for getting input
@@ -87,6 +87,9 @@ outputFileExists() {
   #Strip off srm://hostname:8443 to get raw pnfs path.
   local_fname=${fname#srm://*:8443}
 
+  #Strip off '/blah/blah?SFN='
+  local_fname=${local_fname#*SFN=}
+
   if [ -f "$local_fname" ]; then
     return 0
   fi
@@ -127,7 +130,7 @@ PrintUsage() {
   echo ""
   echo "OPTIONS:"
   echo "  --output-dir=${SRM_HOME}/<jobName>-<runName>"
-  echo "               (the special value '.' copies files back to submit dir)"
+  echo "               (--output-dir=. copies files back to submit dir)"
   echo "  --input-dir=${DCAP_HOME}/<jobName>"
   echo "  --input-dbs-path=/dbs/dataset/path   (in place of --input-dir)"
   echo "  --input-runs=Run1,Run2,...           (must be used with --input-dbs-path)"
@@ -155,12 +158,14 @@ PrintUsage() {
   echo "  --output-files-per-subdir=N (0 for infinite; 500 default)"
   echo "  --job-generates-output-name (don't try to control output file name)"
   echo "  --dbs-service-url=X         (global DBS by default)"
+  echo "  --use-hdfs                  (read/write to /hdfs)"
+  echo "  --use-xrootd-hdfs           (read/write to /hdfs via xrootd)"
   echo ""
   echo "Note that <runName> is taken from the name of the config file."
   exit 2
 }
 
-OPTS=`getopt -o "h" -l "help,output-dir:,input-dir:,submit-dir:,no-submit,job-count:,skip-existing-output,skip-existing-jobs,match-input-files:,exclude-input-files:,input-files-per-job:,disk-requirements:,memory-requirements:,input-file-list:,input-dbs-path:,input-runs:,save-failed-datafiles,save-missing-input-file-list:,assume-input-files-exist,site-requirements:,quick-test,extra-inputs:,accounting-group:,requires-whole-machine,fwklite,output-files-per-subdir:,job-generates-output-name,dbs-service-url:" -- "$@"`
+OPTS=`getopt -o "h" -l "help,output-dir:,input-dir:,submit-dir:,no-submit,job-count:,skip-existing-output,skip-existing-jobs,match-input-files:,exclude-input-files:,input-files-per-job:,disk-requirements:,memory-requirements:,input-file-list:,input-dbs-path:,input-runs:,save-failed-datafiles,save-missing-input-file-list:,assume-input-files-exist,site-requirements:,quick-test,extra-inputs:,accounting-group:,requires-whole-machine,fwklite,output-files-per-subdir:,job-generates-output-name,dbs-service-url:,use-hdfs,use-xrootd-hdfs" -- "$@"`
 if [ $? -ne 0 ]; then PrintUsage; fi
 
 eval set -- "$OPTS"
@@ -224,6 +229,31 @@ do
     --output-files-per-subdir) shift; OUTPUT_FILES_PER_SUBDIR=$1;;
     --job-generates-output-name) JOB_GENERATES_OUTPUT_NAME=1;;
     --dbs-service-url) shift; DBS_URL_ARG="--url=$1";;
+    --use-hdfs)
+        SRM_SERVER=srm://cmshdfs01.hep.wisc.edu:8443/srm/v2/server?SFN=
+        PNFS_HOME=/hdfs/store/user/$USER
+        DCAP_SERVER=
+        PNFS_STORE=/hdfs
+        SRM_HOME=${SRM_SERVER}${PNFS_HOME}
+        DCAP_HOME=${DCAP_SERVER}${PNFS_HOME}
+
+	# The following is required for CMSSW < 6.9.0, because
+	# we rely on fallback to xrootd when /hdfs is not there,
+	# and support for fallback was added in 6.9.0.
+	# TODO: check what version of CMSSW is being used and only
+	# apply this when needed.  Also, find a better way of testing
+	# for /hdfs.
+	SITE_REQUIREMENTS="${SITE_REQUIREMENTS} && TARGET.UidDomain == \"hep.wisc.edu\""
+        ;;
+    --use-xrootd-hdfs)
+        SRM_SERVER=srm://cmshdfs01.hep.wisc.edu:8443/srm/v2/server?SFN=/hdfs
+        PNFS_HOME=/store/user/$USER
+        LOCAL_POSIX_PREFIX=/hdfs
+        DCAP_SERVER=root://cmshdfs01.hep.wisc.edu/
+        PNFS_STORE=
+        SRM_HOME=${SRM_SERVER}${PNFS_HOME}
+        DCAP_HOME=${DCAP_SERVER}${PNFS_HOME}
+        ;;
     --) shift; break;;
     *) die "Unexpected option $1";;
   esac
@@ -302,8 +332,8 @@ OUTPUT_DIR=${OUTPUT_DIR:-${SRM_HOME}/$jobName-$runName}
 INPUT_DIR=${INPUT_DIR:-${DCAP_HOME}/$jobName}
 SUBMIT_DIR=${SUBMIT_DIR:-${SUBMIT_HOME}/$jobName-$runName}
 
-#Strip off dcap://hostname:22125 to get raw pnfs path.
-LOCAL_INPUT_DIR=${INPUT_DIR#dcap://*:22125}
+#Strip off server part of input path
+LOCAL_INPUT_DIR=${INPUT_DIR#$DCAP_SERVER}
 
 #Get the part of INPUT_DIR that was stripped off.
 INPUT_BASE=${INPUT_DIR%$LOCAL_INPUT_DIR}
@@ -313,8 +343,8 @@ if [ "$INPUT_FILE_LIST" != "" ]; then
         die "Error: No such file: $INPUT_FILE_LIST"
     fi
     INPUT_FILE_LIST=`realpath $INPUT_FILE_LIST`
-elif ! [ -d "$LOCAL_INPUT_DIR" ]; then
-  die "Error: No such input directory: $LOCAL_INPUT_DIR"
+elif ! [ -d "${LOCAL_POSIX_PREFIX}${LOCAL_INPUT_DIR}" ]; then
+  die "Error: No such input directory: ${LOCAL_POSIX_PREFIX}${LOCAL_INPUT_DIR}"
 fi
 
 if [ "$INPUT_DBS_PATH" != "" ]; then
@@ -507,7 +537,7 @@ if [ "$EXCLUDE_INPUT_FILES" != "" ]; then
   EXCLUDE_ARG="-not -name $EXCLUDE_INPUT_FILES"
 fi
 
-find_command="find $LOCAL_INPUT_DIR -size +0 -name $MATCH_INPUT_FILES $EXCLUDE_ARG"
+find_command="find ${LOCAL_POSIX_PREFIX}${LOCAL_INPUT_DIR} -size +0 -name $MATCH_INPUT_FILES $EXCLUDE_ARG"
 
 dbs_query() {
     query="find file where"
@@ -541,13 +571,15 @@ do
     i=$INPUT_FILES_PER_JOB
     while [ $i -gt 0 ]; do
         nextInputFileOrigName="${nextInputFile}"
+        nextInputFile="${nextInputFile#$LOCAL_POSIX_PREFIX}"
         if [ "$prepend_local_input_dir" = 1 ]; then
             nextInputFile="${LOCAL_INPUT_DIR}${nextInputFile}"
         fi
+        nextInputFilePosix="${LOCAL_POSIX_PREFIX}${nextInputFile}"
 
         if [ "$check_input_file_existence" = "1" ]; then
-            if ! [ -f "$nextInputFile" ]; then
-                echo "$nextInputFile does not exist, skipping"
+            if ! [ -f "$nextInputFilePosix" ]; then
+                echo "$nextInputFilePosix does not exist, skipping"
 
                 if [ "$SAVE_MISSING_INPUT_FILE_LIST" != "" ]; then
                     echo "$nextInputFileOrigName" >> "$SAVE_MISSING_INPUT_FILE_LIST"
