Added checking for grid proxy of sufficient lifetime and hints to user about what to do about it.

diff --git a/farmoutRandomSeedJobs b/farmoutRandomSeedJobs
--- a/farmoutRandomSeedJobs
+++ b/farmoutRandomSeedJobs
@@ -27,6 +27,7 @@ DCAP_HOME=${DCAP_SERVER}${PNFS_HOME}
 
 DISK_REQUIREMENTS=2000
 MEMORY_REQUIREMENTS=900
+MIN_PROXY_HOURS=24
 
 # special exit status to force job to leave the queue
 FAIL_JOB=42
@@ -55,6 +56,35 @@ outputFileExists() {
     return 0
   fi
   return 1
+}
+
+check_proxy() {
+  hours=$1
+  proxy=$2
+  if ! [ -f "$proxy" ]; then
+    echo
+    echo "NOTE: No grid proxy found.  (Expecting to find it here: $proxy.)"
+    return 1
+  fi
+
+  #Issue a warning if less than this many seconds remain:
+  min_proxy_lifetime=$((3600*$hours))
+
+  seconds_left="`voms-proxy-info --timeleft --file=$proxy 2>/dev/null`"
+
+  if [ "$seconds_left" = "" ]; then
+    echo "WARNING: cannot find time remaining for grid proxy."
+    voms-proxy-info -all -path $proxy
+    return 0
+  fi
+  if [ "$seconds_left" -lt "$min_proxy_lifetime" ]; then
+    echo
+    echo "NOTE: grid proxy is about to expire:"
+    echo "voms-proxy-info"
+    voms-proxy-info --file=$proxy
+    return 1
+  fi
+
 }
 
 PrintUsage() {
@@ -104,7 +134,7 @@ done
 if [ "$#" -ne 5 ]; then PrintUsage; fi
 
 # Check for some required utilities
-for exe in scramv1 condor_submit cmsRun.sh realpath; do
+for exe in scramv1 condor_submit cmsRun.sh realpath voms-proxy-info; do
   if ! which $exe >& /dev/null; then
     echo "Cannot find $exe in PATH.  Your environment is not correctly set up."
     exit 1
@@ -123,6 +153,17 @@ configTemplate=`realpath $5`
 
 if ! [ -d "$CMSSW_HOME" ]; then
   echo "No such directory: $CMSSW_HOME"
+  exit 1
+fi
+
+proxy=${X509_USER_PROXY:-/tmp/x509up_u$UID}
+
+if [ "$NO_SUBMIT" != 1 ] && ! check_proxy $MIN_PROXY_HOURS $proxy; then
+  echo
+  echo "Either rerun this command with --no-submit or create a new grid proxy"
+  echo "and rerun this command.  Example of how to create a grid proxy:"
+  echo
+  echo "voms-proxy-init --voms=cms --hours=48"
   exit 1
 fi
 
@@ -168,8 +209,6 @@ cd $SUBMIT_DIR || die "Failed to create directory $SUBMIT_DIR"
 # Job specification
 #
 Executable=`which cmsRun.sh`
-
-proxy=${X509_USER_PROXY:-/tmp/x509up_u$UID}
 
 #
 # CMS Dashboard parameters
