Added support for .py cfg files.

diff --git a/farmoutAnalysisJobs b/farmoutAnalysisJobs
--- a/farmoutAnalysisJobs
+++ b/farmoutAnalysisJobs
@@ -164,6 +164,7 @@ INPUT_DBS_PATH=
 SAVE_FAILED_DATAFILES=
 SAVE_MISSING_INPUT_FILE_LIST=
 ASSUME_INPUT_FILES_EXIST=
+CFG_EXTENSION=
 
 while [ ! -z "$1" ]
 do
@@ -212,8 +213,26 @@ configTemplate=`realpath $3`
 
 # Now we have all the user's input.
 
+# Check the config template
 
-runName=`basename $configTemplate .cfg`
+if [ "$configTemplate" = "" ]; then
+  die "You must specify a cfg template."
+fi
+
+CFG_EXTENSION="${configTemplate/*./}"
+
+if [ "$CFG_EXTENSION" != "py" ] && [ "$CFG_EXTENSION" != "cfg" ]; then
+  die "cfg template must end in .py or .cfg"
+fi
+
+for macro in \$inputFileNames \$outputFileName; do
+  if ! grep -F -q $macro $configTemplate; then
+    die "$macro must appear on the configuration template.  I can't find it in $configTemplate"
+  fi
+done
+
+
+runName=`basename $configTemplate .${CFG_EXTENSION}`
 
 if [ "$INPUT_DIR" = "" ]; then
     if [ "$INPUT_FILE_LIST" != "" ] || [ "$INPUT_DBS_PATH" != "" ]; then
@@ -270,17 +289,6 @@ if [ "$NO_SUBMIT" != 1 ] && ! check_proxy $MIN_PROXY_HOURS $proxy; then
   exit 1
 fi
 
-# Check the config template
-
-if [ "$configTemplate" = "" ]; then
-  die "You must specify a cfg template."
-fi
-
-for macro in \$inputFileNames \$outputFileName; do
-  if ! grep -F -q $macro $configTemplate; then
-    die "$macro must appear on the configuration template.  I can't find it in $configTemplate"
-  fi
-done
 
 #
 # CMSSW environment setup
@@ -451,7 +459,7 @@ do
     conlog=$jobtag.log
     stdout=$jobtag.out
     stderr=$jobtag.err
-    jobcfg=$jobtag.cfg
+    jobcfg=$jobtag.$CFG_EXTENSION
     outputFileName=$jobtag.root
 
 #
