Switched to random seeds as 32-bit values drawn from /dev/urandom.

diff --git a/farmoutRandomSeedJobs b/farmoutRandomSeedJobs
--- a/farmoutRandomSeedJobs
+++ b/farmoutRandomSeedJobs
@@ -41,13 +41,42 @@ if ! [ -d $scratch_dir ]; then
 fi
 SUBMIT_HOME=${scratch_dir}/$USER
 
+
+# We fork hexdump from a sub-process to avoid annoying
+# job-control message from bash when we kill it off later.
+# Turning off job-control message is not as simple as you
+# might think.  In fact, it does not appear to be possible.
+fork_urandom() {
+  hexdump -e '"%4u\n"' /dev/urandom 5<>${URANDOM} >/dev/fd/5 &
+  echo $!
+}
+# Create a FIFO stream of random 32-bit unsigned integers.
+# To read from it, do read VARNAME < ${URANDOM}
+start_urandom() {
+  URANDOM=/tmp/farmout_urandom.$$
+  mkfifo ${URANDOM}
+  # save the PID so we can shut it down later
+  URANDOM_PID=$( fork_urandom )
+}
+stop_urandom() {
+  if [ "${URANDOM_PID}" != "" ]; then
+    kill ${URANDOM_PID}
+    rm ${URANDOM}
+    unset URANDOM_PID
+    unset URANDOM
+  fi
+}
+
 logerror() {
   echo 2>&1 "$@"
 }
 
 die() {
-  logerror
-  logerror "$@"
+  if [ $# -gt 0 ]; then
+    logerror
+    logerror "$@"
+  fi
+  stop_urandom
   exit 1
 }
 
@@ -74,7 +103,9 @@ check_proxy() {
   hours=$1
   proxy=$2
   if ! [ -f "$proxy" ]; then
-    die "NOTE: No grid proxy found.  (Expecting to find it here: $proxy.)"
+    logerror
+    logerror "NOTE: No grid proxy found.  (Expecting to find it here: $proxy.)"
+    return 1
   fi
 
   #Issue a warning if less than this many seconds remain:
@@ -188,12 +219,6 @@ if ! [ -d "$CMSSW_HOME" ]; then
   die "No such directory: $CMSSW_HOME"
 fi
 
-# randomize
-if [ "$RANDOM" = "" ]; then
-  die "\$RANDOM is not working.  Are you using bash?"
-fi
-RANDOM=`date +%N | cut -c 1-6 | sed 's|^0*||'`
-
 proxy=${X509_USER_PROXY:-/tmp/x509up_u$UID}
 
 if [ "$NO_SUBMIT" != 1 ] && ! check_proxy $MIN_PROXY_HOURS $proxy; then
@@ -202,14 +227,14 @@ if [ "$NO_SUBMIT" != 1 ] && ! check_proxy $MIN_PROXY_HOURS $proxy; then
   logerror "and rerun this command.  Example of how to create a grid proxy:"
   logerror
   logerror "voms-proxy-init --voms=cms --hours=48"
-  exit 1
+  die
 fi
 
 if [ "$EXTRA_INPUTS" != "" ]; then
   for file in ${EXTRA_INPUTS//,/ }; do
     if ! [ -a $file ]; then
       logerror "ERROR: Cannot find file specified in --extra-inputs: $file"
-      exit 1
+      die
     fi
   done
 fi
@@ -273,7 +298,7 @@ if [ -d "$SUBMIT_DIR" ] && [ "$SKIP_EXISTING_JOBS" != "1" ]; then
   logerror
   logerror "You must either remove it, or specify --skip-existing-jobs, or"
   logerror "specify a different job name or submission directory with --submit-dir"
-  exit 1
+  die
 fi
 
 mkdir -p $SUBMIT_DIR
@@ -352,6 +377,8 @@ for template in $chainedConfigs; do
   let final_step=$final_step+1
 done
 
+start_urandom || die "Failed to start up /dev/urandom stream."
+
 #
 # Loop over jobs
 #
@@ -390,10 +417,7 @@ while (( $nEvents > $nEventsSubmitted )); do
     # in order to assure proper treatment of macros that share a common
     # prefix (e.g. randomNumber11 should be replaced before randomNumber1)
     for randomMacro in $randomMacros; do
-        # ${RANDOM} is 15-bit
-	# prepend the job number to it to make sure no two jobs in
-	# a batch have the same seed
-        randomNumber=$(( ${RANDOM} + (${job}<<15) ))
+        read randomNumber < ${URANDOM} || die "Failed to read from urandom."
         randomSed="${randomSed}s/\\${randomMacro}/${randomNumber}/g;"
     done
 
@@ -459,6 +483,8 @@ EOF
     let nEventsSubmitted=$nEventsSubmitted+$nEventsPerJob
 
 done
+
+stop_urandom
 
 #
 # Submit the jobs
